#!/usr/bin/env python
##############################################################################
#
# Copyright (C) Zenoss, Inc. 2021, all rights reserved.
#
# This content is made available according to terms specified in
# License.zenoss under the directory where your Zenoss product is installed.
#
##############################################################################

from twisted.internet import defer

from Products.DataCollector.plugins.DataMaps import ObjectMap
from Products.DataCollector.DeviceProxy import DeviceProxy

ALWAYS_ON_COLLECT_RESULTS = {
    'clear': 'Error parsing zDBInstances',
    'device': ObjectMap(data=dict(sqlhostname='host0')),
    'databases': [],
    'instances': [],
    'jobs': [],
    'backups': [],
    'errors': {},
    'ao_info': {
        'availability_listeners': {
            u'cf2628b9-d180-46e5-9e56-debf65268cd5': {'name': u'TestAG_TestAG', 'dns_name': u'TestAG',
                                                      'network_mode': 1,
                                                      'ag_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1', 'state': 2,
                                                      u'tcp_port': 1433, 'ip_address': u'10.88.123.205',
                                                      'id': u'cf2628b9-d180-46e5-9e56-debf65268cd5'},
            u'5869339c-942f-4ef1-b085-d9718db16cd3': {'name': u'TestAG1_TestAG_Listener',
                                                      'dns_name': u'TestAG_Listener',
                                                      'network_mode': 1,
                                                      'ag_id': u'777c50fd-348e-4686-a622-edd90a4340e1',
                                                      'state': 2, u'tcp_port': 1425, 'ip_address': u'10.88.123.201',
                                                      'id': u'5869339c-942f-4ef1-b085-d9718db16cd3'},
            u'93ac36cf-1da8-4803-957f-60c38cd55983': {'name': u'TestAG_AvailabilityListener1',
                                                      'dns_name': u'TestAG_AvailabilityListener1', 'network_mode': 0,
                                                      'ag_id': u'',  # Empty to check whether it will be skipped
                                                      'state': 2,
                                                      u'tcp_port': 1426, 'ip_address': u'10.88.122.206',
                                                      'id': u'93ac36cf-1da8-4803-957f-60c38cd55983'}}, 'errors': {},
        'availability_groups': {
            u'777c50fd-348e-4686-a622-edd90a4340e1': {'ag_res_id': u'777c50fd-348e-4686-a622-edd90a4340e1',
                                                      u'failure_condition_level': 3, u'is_distributed': False,
                                                      'name': u'TestAG1', u'db_level_health_detection': False,
                                                      u'cluster_type': None,
                                                      u'primary_replica_server_name': u'WSC-NODE-02\\SQLAON',
                                                      'cluster_resource_state': 2,
                                                      u'id': u'b6040ddd-408b-4fe5-a370-0c7c45358ca7',
                                                      u'automated_backup_preference': 2,
                                                      u'health_check_timeout': 30000},
            u'3b504b7c-4fd7-48b8-a445-683ed1a97ba8': {'ag_res_id': u'3b504b7c-4fd7-48b8-a445-683ed1a97ba8',
                                                      u'failure_condition_level': 3, u'is_distributed': False,
                                                      'name': u'SQLAOAG', u'db_level_health_detection': False,
                                                      u'cluster_type': None,
                                                      u'primary_replica_server_name': u'WSC-NODE-01\\SQLAO',
                                                      'cluster_resource_state': 2,
                                                      u'id': u'cf6f5be1-ab56-4624-a471-5831671f454a',
                                                      u'automated_backup_preference': 2,
                                                      u'health_check_timeout': 30000},
            u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1': {'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1',
                                                      u'failure_condition_level': 3, u'is_distributed': False,
                                                      'name': u'TestAG', u'db_level_health_detection': True,
                                                      u'cluster_type': None,
                                                      u'primary_replica_server_name': u'WSC-NODE-01\\SQLAON',
                                                      'cluster_resource_state': 2,
                                                      u'id': u'd3313358-3897-492c-9e65-3e4af421e7a3',
                                                      u'automated_backup_preference': 2,
                                                      u'health_check_timeout': 30000}}, 'sql_instances': {
            u'WSC-NODE-03\\SQLAON': {'sql_server_instance_full_name': u'WSC-NODE-03\\SQLAON', 'is_on_wsfc': None,
                                     'sql_hostname_fqdn': 'wsc-node-03.sol-win.lab',
                                     u'sql_server_fullname': u'WSC-NODE-03\\SQLAON',
                                     'sql_server_version': u'13.0.1601.5', 'is_clustered_instance': False,
                                     'instance_name': u'SQLAON', 'sqlhostname': u'wsc-node-03',
                                     'sql_server_name': u'WSC-NODE-03\\SQLAON', 'instance_original_name': u'SQLAON',
                                     'sql_host_ip': u'10.88.122.133', u'sql_server_node': u'wsc-node-03'},
            u'WSC-NODE-02\\SQLAON': {'sql_server_instance_full_name': u'WSC-NODE-02\\SQLAON', 'is_on_wsfc': None,
                                     'sql_hostname_fqdn': 'wsc-node-02.sol-win.lab',
                                     u'sql_server_fullname': u'WSC-NODE-02\\SQLAON',
                                     'sql_server_version': u'13.0.1601.5', 'is_clustered_instance': False,
                                     'instance_name': u'SQLAON', 'sqlhostname': u'wsc-node-02',
                                     'sql_server_name': u'WSC-NODE-02\\SQLAON', 'instance_original_name': u'SQLAON',
                                     'sql_host_ip': u'10.88.122.132', u'sql_server_node': u'wsc-node-02'},
            u'WSC-NODE-02\\SQLAO': {'sql_server_instance_full_name': u'WSC-NODE-02\\SQLAO',
                                    'sql_hostname_fqdn': 'wsc-node-02.sol-win.lab',
                                    u'sql_server_fullname': u'WSC-NODE-02\\SQLAO', 'sql_server_version': u'13.0.1601.5',
                                    'instance_name': u'SQLAO', 'sqlhostname': u'wsc-node-02',
                                    'sql_server_name': u'WSC-NODE-02\\SQLAO', 'instance_original_name': u'SQLAO',
                                    'sql_host_ip': u'10.88.122.132', u'sql_server_node': u'wsc-node-02'},
            u'WSC-NODE-01\\SQLAON': {'sql_server_instance_full_name': u'WSC-NODE-01\\SQLAON', 'is_on_wsfc': None,
                                     'sql_hostname_fqdn': 'wsc-node-01.sol-win.lab',
                                     u'sql_server_fullname': u'WSC-NODE-01\\SQLAON',
                                     'sql_server_version': u'13.0.1601.5', 'is_clustered_instance': False,
                                     'instance_name': u'SQLAON', 'sqlhostname': u'wsc-node-01',
                                     'sql_server_name': u'WSC-NODE-01\\SQLAON', 'instance_original_name': u'SQLAON',
                                     'sql_host_ip': u'10.88.122.131', u'sql_server_node': u'wsc-node-01'},
            u'WSC-NODE-01\\SQLAO': {'sql_server_instance_full_name': u'WSC-NODE-01\\SQLAO', 'is_on_wsfc': None,
                                    'sql_hostname_fqdn': 'wsc-node-01.sol-win.lab',
                                    u'sql_server_fullname': u'WSC-NODE-01\\SQLAO', 'sql_server_version': u'13.0.1601.5',
                                    'is_clustered_instance': False, 'instance_name': u'SQLAO',
                                    'sqlhostname': u'wsc-node-01', 'sql_server_name': u'WSC-NODE-01\\SQLAO',
                                    'instance_original_name': u'SQLAO', 'sql_host_ip': u'10.88.122.131',
                                    u'sql_server_node': u'wsc-node-01'}}, 'availability_databases': {
            (u'WSC-NODE-01\\SQLAON', 7): {u'ag_res_id': u'777c50fd-348e-4686-a622-edd90a4340e1', u'sync_state': 2,
                                          u'db_id': 7,
                                          u'name': u'test_alwayson_db_3', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1607071252.6299999, u'suspended': False,
                                          u'lastbackupdate': 1607071252,
                                          u'owner': u'sa', u'defaultfilegroup': None, u'version': 852,
                                          u'isaccessible': False,
                                          u'systemobject': False, u'adb_id': u'85dc383a-bf7b-4ab7-8cea-cc52919bdb36',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'WSC-NODE-03\\SQLAON', 7): {u'ag_res_id': u'777c50fd-348e-4686-a622-edd90a4340e1', u'sync_state': 2,
                                          u'db_id': 7,
                                          u'name': u'test_alwayson_db_3', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1607068113.9329998, u'suspended': False,
                                          u'lastbackupdate': 1607071252,
                                          u'owner': u'SOL-WIN\\Administrator', u'defaultfilegroup': None,
                                          u'version': 852,
                                          u'isaccessible': False, u'systemobject': False,
                                          u'adb_id': u'85dc383a-bf7b-4ab7-8cea-cc52919bdb36',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'WSC-NODE-01\\SQLAON', 6): {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1', u'sync_state': 2,
                                          u'db_id': 6,
                                          u'name': u'test_alwayson_db_2', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1606980227.29, u'suspended': False,
                                          u'lastbackupdate': 1607053473,
                                          u'owner': u'SOL-WIN\\Administrator', u'defaultfilegroup': u'PRIMARY',
                                          u'version': 852,
                                          u'isaccessible': True, u'systemobject': False,
                                          u'adb_id': u'49e5c917-8ca9-4b46-b2e8-e25d9ee711e8',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'WSC-NODE-03\\SQLAON', 6): {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1', u'sync_state': 1,
                                          u'db_id': 6,
                                          u'name': u'test_alwayson_db_1', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1607053472.737, u'suspended': False,
                                          u'lastbackupdate': 1607053473,
                                          u'owner': u'sa', u'defaultfilegroup': None, u'version': 852,
                                          u'isaccessible': False,
                                          u'systemobject': False, u'adb_id': u'69945148-b97e-4132-b9fc-e6a6a19bb6ef',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'WSC-NODE-03\\SQLAON', 5): {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1', u'sync_state': 1,
                                          u'db_id': 5,
                                          u'name': u'test_alwayson_db_2', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1607053472.737, u'suspended': False,
                                          u'lastbackupdate': 1607053473,
                                          u'owner': u'sa', u'defaultfilegroup': None, u'version': 852,
                                          u'isaccessible': False,
                                          u'systemobject': False, u'adb_id': u'49e5c917-8ca9-4b46-b2e8-e25d9ee711e8',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'WSC-NODE-02\\SQLAON', 6): {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1', u'sync_state': 1,
                                          u'db_id': 6,
                                          u'name': u'test_alwayson_db_2', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1607053472.6569998, u'suspended': False,
                                          u'lastbackupdate': 1607053472,
                                          u'owner': u'sa', u'defaultfilegroup': u'PRIMARY', u'version': 852,
                                          u'isaccessible': True, u'systemobject': False,
                                          u'adb_id': u'49e5c917-8ca9-4b46-b2e8-e25d9ee711e8',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'WSC-NODE-02\\SQLAON', 7): {u'ag_res_id': u'777c50fd-348e-4686-a622-edd90a4340e1', u'sync_state': 2,
                                          u'db_id': 7,
                                          u'name': u'test_alwayson_db_3', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1607071252.287, u'suspended': False,
                                          u'lastbackupdate': 1607071252,
                                          u'owner': u'sa', u'defaultfilegroup': u'PRIMARY', u'version': 852,
                                          u'isaccessible': True, u'systemobject': False,
                                          u'adb_id': u'85dc383a-bf7b-4ab7-8cea-cc52919bdb36',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'', 5):  # Empty to check whether this will be skipped
                {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1', u'sync_state': 1,
                                          u'db_id': 5,
                                          u'name': u'test_alwayson_db_1', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1607053472.6569998, u'suspended': False,
                                          u'lastbackupdate': 1607053472,
                                          u'owner': u'sa', u'defaultfilegroup': u'PRIMARY', u'version': 852,
                                          u'isaccessible': True, u'systemobject': False,
                                          u'adb_id': u'69945148-b97e-4132-b9fc-e6a6a19bb6ef',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1},
            (u'WSC-NODE-01\\SQLAON', 5): {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1', u'sync_state': 2,
                                          u'db_id': 5,
                                          u'name': u'test_alwayson_db_1', u'lastlogbackupdate': -62135596800,
                                          u'createdate': 1606976235.56, u'suspended': False,
                                          u'lastbackupdate': 1607053473,
                                          u'owner': u'SOL-WIN\\Administrator', u'defaultfilegroup': u'PRIMARY',
                                          u'version': 852,
                                          u'isaccessible': True, u'systemobject': False,
                                          u'adb_id': u'69945148-b97e-4132-b9fc-e6a6a19bb6ef',
                                          u'collation': u'SQL_Latin1_General_CP1_CI_AS',
                                          u'primaryfilepath': u'C:\\Program Files\\Microsoft SQL Server\\MSSQL13.SQLAON\\MSSQL\\DATA',
                                          u'recoverymodel': 1}}, 'availability_replicas': {
            u'4ab18693-439c-4e4c-acec-6abc7a91928f': {u'ag_res_id': u'3b504b7c-4fd7-48b8-a445-683ed1a97ba8',
                                                      u'name': u'WSC-NODE-01\\SQLAO',
                                                      u'replica_server_name': u'WSC-NODE-01\\SQLAO',
                                                      u'endpoint_url': u'TCP://wsc-node-01.sol-win.lab:5022',
                                                      u'ag_id': u'cf6f5be1-ab56-4624-a471-5831671f454a',
                                                      u'id': u'4ab18693-439c-4e4c-acec-6abc7a91928f',
                                                      u'replica_server_hostname': u'wsc-node-01'},
            u'106864b6-f741-4b3c-b6be-48daa15ff3d7': {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1',
                                                      u'name': u'WSC-NODE-03\\SQLAON',
                                                      u'replica_server_name': u'WSC-NODE-03\\SQLAON',
                                                      u'endpoint_url': u'TCP://wsc-node-03.sol-win.lab:5023',
                                                      u'ag_id': u'd3313358-3897-492c-9e65-3e4af421e7a3',
                                                      u'id': u'106864b6-f741-4b3c-b6be-48daa15ff3d7',
                                                      u'replica_server_hostname': u'wsc-node-03'},
            u'510295f7-5ef9-4cfd-ba99-e45e3e860c5f': {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1',
                                                      u'name': u'WSC-NODE-02\\SQLAON',
                                                      u'replica_server_name': u'WSC-NODE-02\\SQLAON',
                                                      u'endpoint_url': u'TCP://wsc-node-02.sol-win.lab:5023',
                                                      u'ag_id': u'd3313358-3897-492c-9e65-3e4af421e7a3',
                                                      u'id': u'510295f7-5ef9-4cfd-ba99-e45e3e860c5f',
                                                      u'replica_server_hostname': u'wsc-node-02'},
            u'd97da9be-1c80-439d-bb19-11bc5c5f5083': {u'ag_res_id': u'777c50fd-348e-4686-a622-edd90a4340e1',
                                                      u'name': u'WSC-NODE-03\\SQLAON',
                                                      u'replica_server_name': u'WSC-NODE-03\\SQLAON',
                                                      u'endpoint_url': u'TCP://wsc-node-03.sol-win.lab:5023',
                                                      u'ag_id': u'b6040ddd-408b-4fe5-a370-0c7c45358ca7',
                                                      u'id': u'd97da9be-1c80-439d-bb19-11bc5c5f5083',
                                                      u'replica_server_hostname': u'wsc-node-03'},
            u'173ce86b-abdc-4ca2-984a-ade7950c55d1': {u'ag_res_id': u'777c50fd-348e-4686-a622-edd90a4340e1',
                                                      u'name': u'WSC-NODE-02\\SQLAON',
                                                      u'replica_server_name': u'WSC-NODE-02\\SQLAON',
                                                      u'endpoint_url': u'TCP://wsc-node-02.sol-win.lab:5023',
                                                      u'ag_id': u'b6040ddd-408b-4fe5-a370-0c7c45358ca7',
                                                      u'id': u'173ce86b-abdc-4ca2-984a-ade7950c55d1',
                                                      u'replica_server_hostname': u'wsc-node-02'},
            u'b78190e7-2518-4ab8-b5ed-0cf3c4c54f9a': {u'ag_res_id': u'0b38a4e4-8c30-46e8-873e-7cd1b397bfc1',
                                                      u'name': u'WSC-NODE-01\\SQLAON',
                                                      u'replica_server_name': u'WSC-NODE-01\\SQLAON',
                                                      u'endpoint_url': u'TCP://wsc-node-01.sol-win.lab:5023',
                                                      u'ag_id': u'd3313358-3897-492c-9e65-3e4af421e7a3',
                                                      u'id': u'b78190e7-2518-4ab8-b5ed-0cf3c4c54f9a',
                                                      u'replica_server_hostname': u'wsc-node-01'},
            u'd8cca389-7ed9-4531-b723-4cfac6f13f21': {u'ag_res_id': u'3b504b7c-4fd7-48b8-a445-683ed1a97ba8',
                                                      u'name': u'WSC-NODE-02\\SQLAO',
                                                      u'replica_server_name': u'WSC-NODE-02\\SQLAO',
                                                      u'endpoint_url': u'TCP://wsc-node-02.sol-win.lab:5022',
                                                      u'ag_id': u'cf6f5be1-ab56-4624-a471-5831671f454a',
                                                      u'id': u'd8cca389-7ed9-4531-b723-4cfac6f13f21',
                                                      u'replica_server_hostname': u'wsc-node-02'},
            u'4dd141b8-e88f-46ed-b160-b71f2f588162': {u'ag_res_id': u'',  # Empty to check whether this will be skipped
                                                      u'name': u'WSC-NODE-01\\SQLAON',
                                                      u'replica_server_name': u'WSC-NODE-01\\SQLAON',
                                                      u'endpoint_url': u'TCP://wsc-node-01.sol-win.lab:5023',
                                                      u'ag_id': u'b6040ddd-408b-4fe5-a370-0c7c45358ca7',
                                                      u'id': u'4dd141b8-e88f-46ed-b160-b71f2f588162',
                                                      u'replica_server_hostname': u'wsc-node-01'}}}}

HOST_USER_NAME = 'test@test.domain'
HOST_USER_PASSWORD = 'test_password'

DB_LOGINS = {u'MSSQLSERVER': {'username': HOST_USER_NAME, 'login_as_user': True,
                              'password': HOST_USER_PASSWORD}}


class DummyClass(object):
    """
    Class which will be filled by data from dict. Need where calling code expect object rather than dict.
    """
    pass


class ObjectFromDictProducer(object):

    @staticmethod
    def object_from_dict(data):
        result_object = DummyClass()

        for key, value in data.iteritems():
            setattr(result_object, key, value)

        return result_object


class DummySQLCommander(ObjectFromDictProducer):
    """
    Custom WinRS client replacement for testing purposes.
    """

    def __init__(self, conn_info=None, log=None):
        self._conn_info = conn_info
        self.log = log

    def create_sql_commander_response(self, data):
        """
        Returns DummyClass object because the calling code expect object, not a dict.
        :param data: dict
        :return: DummyClass
        """
        return self.object_from_dict(data)

    @defer.inlineCallbacks
    def defer_sql_commander_response(self, response):
        response_generator = yield response
        defer.returnValue(response_generator)

    def get_availability_group_cluster_resources(self):

        response = {'exit_code': 0,
                    'stderr': [],
                    'stdout': [u'[',
                               u'{',
                               u'"ag_name":  "SQLAOAG",',
                               u'"ag_resource_id":  "3b504b7c-4fd7-48b8-a445-683ed1a97ba8",',
                               u'"ag_resource_state":  2,',
                               u'"owner_nodes_info":  [',
                               u'{',
                               u'"OwnerNode":  "wsc-node-01",',
                               u'"OwnerNodeFQDN":  "wsc-node-01.sol-win.lab",',
                               u'"OwnerNodeDomain":  "sol-win.lab",',
                               u'"IPv4":  "10.88.122.131"',
                               u'},',
                               u'{',
                               u'"OwnerNode":  "wsc-node-02",',
                               u'"OwnerNodeFQDN":  "wsc-node-02.sol-win.lab",',
                               u'"OwnerNodeDomain":  "sol-win.lab",',
                               u'"IPv4":  "10.88.122.132"',
                               u'}',
                               u'],',
                               u'"listeners_info":  [',
                               u']',
                               u'},',
                               u'{',
                               u'"ag_name":  "TestAG",',
                               u'"ag_resource_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                               u'"ag_resource_state":  2,',
                               u'"owner_nodes_info":  [',
                               u'{',
                               u'"OwnerNode":  "wsc-node-01",',
                               u'"OwnerNodeFQDN":  "wsc-node-01.sol-win.lab",',
                               u'"OwnerNodeDomain":  "sol-win.lab",',
                               u'"IPv4":  "10.88.122.131"',
                               u'}',
                               u'],',
                               u'"listeners_info":  [',
                               u'{',
                               u'"id":  "cf2628b9-d180-46e5-9e56-debf65268cd5",',
                               u'"ag_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                               u'"name":  "TestAG_TestAG",',
                               u'"dns_name":  "TestAG",',
                               u'"state":  2,',
                               u'"ip_address":  "10.88.123.205",',
                               u'"network_mode":  1',
                               u'},',
                               u'{',
                               u'"id":  "93ac36cf-1da8-4803-957f-60c38cd55983",',
                               u'"ag_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                               u'"name":  "TestAG_AvailabilityListener1",',
                               u'"dns_name":  "TestAG_AvailabilityListener1",',
                               u'"state":  2,',
                               u'"ip_address":  "10.88.122.206",',
                               u'"network_mode":  0',
                               u'}',
                               u']',
                               u'},',
                               u'{',
                               u'"ag_name":  "TestAG1",',
                               u'"ag_resource_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                               u'"ag_resource_state":  2,',
                               u'"owner_nodes_info":  [',
                               u'{',
                               u'"OwnerNode":  "wsc-node-01",',
                               u'"OwnerNodeFQDN":  "wsc-node-01.sol-win.lab",',
                               u'"OwnerNodeDomain":  "sol-win.lab",',
                               u'"IPv4":  "10.88.122.131"',
                               u'},',
                               u'{',
                               u'"OwnerNode":  "wsc-node-02",',
                               u'"OwnerNodeFQDN":  "wsc-node-02.sol-win.lab",',
                               u'"OwnerNodeDomain":  "sol-win.lab",',
                               u'"IPv4":  "10.88.122.132"',
                               u'},',
                               u'{',
                               u'"OwnerNode":  "wsc-node-03",',
                               u'"OwnerNodeFQDN":  "wsc-node-03.sol-win.lab",',
                               u'"OwnerNodeDomain":  "sol-win.lab",',
                               u'"IPv4":  "10.88.122.133"',
                               u'}',
                               u'],',
                               u'"listeners_info":  [',
                               u'{',
                               u'"id":  "5869339c-942f-4ef1-b085-d9718db16cd3",',
                               u'"ag_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                               u'"name":  "TestAG1_TestAG_Listener",',
                               u'"dns_name":  "TestAG_Listener",',
                               u'"state":  2,',
                               u'"ip_address":  "10.88.123.201",',
                               u'"network_mode":  1',
                               u'}',
                               u']',
                               u'}',
                               u']']}

        response_object = self.create_sql_commander_response(response)

        return self.defer_sql_commander_response(response_object)

    def get_always_on_resources_on_node(self, ag_resource_ids=None):

        win_node = self._conn_info.hostname

        response = {
            'wsc-node-01.sol-win.lab':
                {'exit_code': 0,
                 'stderr': [],
                 'stdout': [u'{', u'"hostname":  "wsc-node-01",', u'"ao_instances":  {', u'"WSC-NODE-02\\\\SQLAON":  {',
                            u'"sql_server_fullname":  "WSC-NODE-02\\\\SQLAON",', u'"sql_server_node":  "wsc-node-02"',
                            u'},', u'"WSC-NODE-01\\\\SQLAON":  {', u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAON",',
                            u'"sql_server_node":  "wsc-node-01"', u'},', u'"WSC-NODE-03\\\\SQLAON":  {',
                            u'"sql_server_fullname":  "WSC-NODE-03\\\\SQLAON",', u'"sql_server_node":  "wsc-node-03"',
                            u'},', u'"WSC-NODE-01\\\\SQLAO":  {', u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAO",',
                            u'"sql_server_node":  "wsc-node-01"', u'},', u'"WSC-NODE-02\\\\SQLAO":  {',
                            u'"sql_server_fullname":  "WSC-NODE-02\\\\SQLAO",', u'"sql_server_node":  "wsc-node-02"',
                            u'}', u'},', u'"instances":  [', u'{', u'"name":  "SQLAO",', u'"version":  "13.0.1601.5"',
                            u'},', u'{', u'"name":  "SQLAON",', u'"version":  "13.0.1601.5"', u'}', u']', u'}']},

            'wsc-node-02.sol-win.lab':
                {'exit_code': 0,
                 'stderr': [],
                 'stdout': [u'{', u'"hostname":  "wsc-node-02",', u'"ao_instances":  {', u'"WSC-NODE-02\\\\SQLAON":  {',
                            u'"sql_server_fullname":  "WSC-NODE-02\\\\SQLAON",', u'"sql_server_node":  "wsc-node-02"',
                            u'},', u'"WSC-NODE-01\\\\SQLAON":  {', u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAON",',
                            u'"sql_server_node":  "wsc-node-01"', u'},', u'"WSC-NODE-03\\\\SQLAON":  {',
                            u'"sql_server_fullname":  "WSC-NODE-03\\\\SQLAON",', u'"sql_server_node":  "wsc-node-03"',
                            u'},', u'"WSC-NODE-01\\\\SQLAO":  {', u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAO",',
                            u'"sql_server_node":  "wsc-node-01"', u'},', u'"WSC-NODE-02\\\\SQLAO":  {',
                            u'"sql_server_fullname":  "WSC-NODE-02\\\\SQLAO",', u'"sql_server_node":  "wsc-node-02"',
                            u'}', u'},', u'"instances":  [', u'{', u'"name":  "SQLAO",', u'"version":  "13.0.1601.5"',
                            u'},', u'{', u'"name":  "SQLAON",', u'"version":  "13.0.1601.5"', u'}', u']', u'}']},

            'wsc-node-03.sol-win.lab':
                {'exit_code': 0,
                 'stderr': [],
                 'stdout': [u'{', u'"hostname":  "wsc-node-03",', u'"ao_instances":  {',
                            u'"WSC-NODE-02\\\\SQLAON":  {',
                            u'"sql_server_fullname":  "WSC-NODE-02\\\\SQLAON",',
                            u'"sql_server_node":  "wsc-node-02"',
                            u'},', u'"WSC-NODE-01\\\\SQLAON":  {',
                            u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAON",',
                            u'"sql_server_node":  "wsc-node-01"', u'},', u'"WSC-NODE-03\\\\SQLAON":  {',
                            u'"sql_server_fullname":  "WSC-NODE-03\\\\SQLAON",',
                            u'"sql_server_node":  "wsc-node-03"',
                            u'},', u'"WSC-NODE-01\\\\SQLAO":  {', u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAO",',
                            u'"sql_server_node":  "wsc-node-01"', u'},', u'"WSC-NODE-02\\\\SQLAO":  {',
                            u'"sql_server_fullname":  "WSC-NODE-02\\\\SQLAO",', u'"sql_server_node":  "wsc-node-02"',
                            u'}',
                            u'},', u'"instances":  [', u'{', u'"name":  "SQLAO",', u'"version":  "13.0.1601.5"',
                            u'},',
                            u'{', u'"name":  "SQLAON",', u'"version":  "13.0.1601.5"', u'}', u']', u'}']}
        }

        response_data_for_node = response.get(win_node, {})
        response_object = self.create_sql_commander_response(response_data_for_node)

        return self.defer_sql_commander_response(response_object)

    def get_availability_group_info(self, sql_connection, sql_server_version=None):

        sql_instance_connections_string = ''.join(sql_connection)

        response = {
            'wsc-node-03\\SQLAON': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"ao_enabled":  true,',
                           u'"sql_server_fullname":  "WSC-NODE-03\\\\SQLAON",',
                           u'"is_clustered":  false,',
                           u'"is_on_wsfc":  null,',
                           u'"availability_groups":  [',
                           u'{',
                           u'"name":  "TestAG",',
                           u'"id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"primary_replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"is_distributed":  false,',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"failure_condition_level":  3,',
                           u'"cluster_type":  null,',
                           u'"db_level_health_detection":  true',
                           u'},',
                           u'{',
                           u'"name":  "TestAG1",',
                           u'"id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"primary_replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"is_distributed":  false,',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"failure_condition_level":  3,',
                           u'"cluster_type":  null,',
                           u'"db_level_health_detection":  false',
                           u'}',
                           u'],',
                           u'"availability_replicas":  [',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "b78190e7-2518-4ab8-b5ed-0cf3c4c54f9a",',
                           u'"name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-01.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-01"',
                           u'},',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "510295f7-5ef9-4cfd-ba99-e45e3e860c5f",',
                           u'"name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-02.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-02"',
                           u'},',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "106864b6-f741-4b3c-b6be-48daa15ff3d7",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-03.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-03"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "4dd141b8-e88f-46ed-b160-b71f2f588162",',
                           u'"name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-01.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-01"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "173ce86b-abdc-4ca2-984a-ade7950c55d1",',
                           u'"name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-02.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-02"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "d97da9be-1c80-439d-bb19-11bc5c5f5083",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-03.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-03"',
                           u'}',
                           u'],',
                           u'"availability_databases":  [',
                           u'{',
                           u'"adb_id":  "69945148-b97e-4132-b9fc-e6a6a19bb6ef",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"name":  "test_alwayson_db_1",',
                           u'"sync_state":  1,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  false,',
                           u'"db_id":  6,',
                           u'"owner":  "sa",',
                           u'"lastbackupdate":  1607053473,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1607053472.737,',
                           u'"defaultfilegroup":  null,',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'},',
                           u'{',
                           u'"adb_id":  "49e5c917-8ca9-4b46-b2e8-e25d9ee711e8",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"name":  "test_alwayson_db_2",',
                           u'"sync_state":  1,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  false,',
                           u'"db_id":  5,',
                           u'"owner":  "sa",',
                           u'"lastbackupdate":  1607053473,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1607053472.737,',
                           u'"defaultfilegroup":  null,',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'},',
                           u'{',
                           u'"adb_id":  "85dc383a-bf7b-4ab7-8cea-cc52919bdb36",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"name":  "test_alwayson_db_3",',
                           u'"sync_state":  2,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  false,',
                           u'"db_id":  7,',
                           u'"owner":  "SOL-WIN\\\\Administrator",',
                           u'"lastbackupdate":  1607071252,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1607068113.9329998,',
                           u'"defaultfilegroup":  null,',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'}',
                           u'],',
                           u'"availability_listeners":  [',
                           u'{',
                           u'"id":  "cf2628b9-d180-46e5-9e56-debf65268cd5",',
                           u'"tcp_port":  1433',
                           u'},',
                           u'{',
                           u'"id":  "93ac36cf-1da8-4803-957f-60c38cd55983",',
                           u'"tcp_port":  1426',
                           u'},',
                           u'{',
                           u'"id":  "5869339c-942f-4ef1-b085-d9718db16cd3",',
                           u'"tcp_port":  1425',
                           u'}',
                           u']',
                           u'}']},

            'wsc-node-01\\SQLAO': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"ao_enabled":  true,',
                           u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAO",',
                           u'"is_clustered":  false,',
                           u'"is_on_wsfc":  null,',
                           u'"availability_groups":  [',
                           u'{',
                           u'"name":  "SQLAOAG",',
                           u'"id":  "cf6f5be1-ab56-4624-a471-5831671f454a",',
                           u'"ag_res_id":  "3b504b7c-4fd7-48b8-a445-683ed1a97ba8",',
                           u'"primary_replica_server_name":  "WSC-NODE-01\\\\SQLAO",',
                           u'"is_distributed":  false,',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"failure_condition_level":  3,',
                           u'"cluster_type":  null,',
                           u'"db_level_health_detection":  false',
                           u'}',
                           u'],',
                           u'"availability_replicas":  [',
                           u'{',
                           u'"ag_id":  "cf6f5be1-ab56-4624-a471-5831671f454a",',
                           u'"ag_res_id":  "3b504b7c-4fd7-48b8-a445-683ed1a97ba8",',
                           u'"id":  "4ab18693-439c-4e4c-acec-6abc7a91928f",',
                           u'"name":  "WSC-NODE-01\\\\SQLAO",',
                           u'"endpoint_url":  "TCP://wsc-node-01.sol-win.lab:5022",',
                           u'"replica_server_name":  "WSC-NODE-01\\\\SQLAO",',
                           u'"replica_server_hostname":  "wsc-node-01"',
                           u'},',
                           u'{',
                           u'"ag_id":  "cf6f5be1-ab56-4624-a471-5831671f454a",',
                           u'"ag_res_id":  "3b504b7c-4fd7-48b8-a445-683ed1a97ba8",',
                           u'"id":  "d8cca389-7ed9-4531-b723-4cfac6f13f21",',
                           u'"name":  "WSC-NODE-02\\\\SQLAO",',
                           u'"endpoint_url":  "TCP://wsc-node-02.sol-win.lab:5022",',
                           u'"replica_server_name":  "WSC-NODE-02\\\\SQLAO",',
                           u'"replica_server_hostname":  "wsc-node-02"',
                           u'}',
                           u'],',
                           u'"availability_databases":  [',
                           u'],',
                           u'"availability_listeners":  [',
                           u']',
                           u'}']},

            'wsc-node-01\\SQLAON': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"ao_enabled":  true,',
                           u'"sql_server_fullname":  "WSC-NODE-01\\\\SQLAON",',
                           u'"is_clustered":  false,',
                           u'"is_on_wsfc":  null,',
                           u'"availability_groups":  [',
                           u'{',
                           u'"name":  "TestAG",',
                           u'"id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"primary_replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"is_distributed":  false,',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"failure_condition_level":  3,',
                           u'"cluster_type":  null,',
                           u'"db_level_health_detection":  true',
                           u'},',
                           u'{',
                           u'"name":  "TestAG1",',
                           u'"id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"primary_replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"is_distributed":  false,',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"failure_condition_level":  3,',
                           u'"cluster_type":  null,',
                           u'"db_level_health_detection":  false',
                           u'}',
                           u'],',
                           u'"availability_replicas":  [',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "b78190e7-2518-4ab8-b5ed-0cf3c4c54f9a",',
                           u'"name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-01.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-01"',
                           u'},',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "510295f7-5ef9-4cfd-ba99-e45e3e860c5f",',
                           u'"name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-02.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-02"',
                           u'},',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "106864b6-f741-4b3c-b6be-48daa15ff3d7",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-03.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-03"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "4dd141b8-e88f-46ed-b160-b71f2f588162",',
                           u'"name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-01.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-01"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "173ce86b-abdc-4ca2-984a-ade7950c55d1",',
                           u'"name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-02.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-02"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "d97da9be-1c80-439d-bb19-11bc5c5f5083",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-03.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-03"',
                           u'}',
                           u'],',
                           u'"availability_databases":  [',
                           u'{',
                           u'"adb_id":  "69945148-b97e-4132-b9fc-e6a6a19bb6ef",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"name":  "test_alwayson_db_1",',
                           u'"sync_state":  2,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  true,',
                           u'"db_id":  5,',
                           u'"owner":  "SOL-WIN\\\\Administrator",',
                           u'"lastbackupdate":  1607053473,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1606976235.56,',
                           u'"defaultfilegroup":  "PRIMARY",',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'},',
                           u'{',
                           u'"adb_id":  "49e5c917-8ca9-4b46-b2e8-e25d9ee711e8",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"name":  "test_alwayson_db_2",',
                           u'"sync_state":  2,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  true,',
                           u'"db_id":  6,',
                           u'"owner":  "SOL-WIN\\\\Administrator",',
                           u'"lastbackupdate":  1607053473,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1606980227.29,',
                           u'"defaultfilegroup":  "PRIMARY",',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'},',
                           u'{',
                           u'"adb_id":  "85dc383a-bf7b-4ab7-8cea-cc52919bdb36",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"name":  "test_alwayson_db_3",',
                           u'"sync_state":  2,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  false,',
                           u'"db_id":  7,',
                           u'"owner":  "sa",',
                           u'"lastbackupdate":  1607071252,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1607071252.6299999,',
                           u'"defaultfilegroup":  null,',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'}',
                           u'],',
                           u'"availability_listeners":  [',
                           u'{',
                           u'"id":  "cf2628b9-d180-46e5-9e56-debf65268cd5",',
                           u'"tcp_port":  1433',
                           u'},',
                           u'{',
                           u'"id":  "93ac36cf-1da8-4803-957f-60c38cd55983",',
                           u'"tcp_port":  1426',
                           u'},',
                           u'{',
                           u'"id":  "5869339c-942f-4ef1-b085-d9718db16cd3",',
                           u'"tcp_port":  1425',
                           u'}',
                           u']',
                           u'}']},

            'wsc-node-02\\SQLAON': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"ao_enabled":  true,',
                           u'"sql_server_fullname":  "WSC-NODE-02\\\\SQLAON",',
                           u'"is_clustered":  false,',
                           u'"is_on_wsfc":  null,',
                           u'"availability_groups":  [',
                           u'{',
                           u'"name":  "TestAG",',
                           u'"id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"primary_replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"is_distributed":  false,',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"failure_condition_level":  3,',
                           u'"cluster_type":  null,',
                           u'"db_level_health_detection":  true',
                           u'},',
                           u'{',
                           u'"name":  "TestAG1",',
                           u'"id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"primary_replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"is_distributed":  false,',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"failure_condition_level":  3,',
                           u'"cluster_type":  null,',
                           u'"db_level_health_detection":  false',
                           u'}',
                           u'],',
                           u'"availability_replicas":  [',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "b78190e7-2518-4ab8-b5ed-0cf3c4c54f9a",',
                           u'"name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-01.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-01"',
                           u'},',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "510295f7-5ef9-4cfd-ba99-e45e3e860c5f",',
                           u'"name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-02.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-02"',
                           u'},',
                           u'{',
                           u'"ag_id":  "d3313358-3897-492c-9e65-3e4af421e7a3",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"id":  "106864b6-f741-4b3c-b6be-48daa15ff3d7",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-03.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-03"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "4dd141b8-e88f-46ed-b160-b71f2f588162",',
                           u'"name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-01.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-01\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-01"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "173ce86b-abdc-4ca2-984a-ade7950c55d1",',
                           u'"name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-02.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-02"',
                           u'},',
                           u'{',
                           u'"ag_id":  "b6040ddd-408b-4fe5-a370-0c7c45358ca7",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"id":  "d97da9be-1c80-439d-bb19-11bc5c5f5083",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"endpoint_url":  "TCP://wsc-node-03.sol-win.lab:5023",',
                           u'"replica_server_name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"replica_server_hostname":  "wsc-node-03"',
                           u'}',
                           u'],',
                           u'"availability_databases":  [',
                           u'{',
                           u'"adb_id":  "69945148-b97e-4132-b9fc-e6a6a19bb6ef",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"name":  "test_alwayson_db_1",',
                           u'"sync_state":  1,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  true,',
                           u'"db_id":  5,',
                           u'"owner":  "sa",',
                           u'"lastbackupdate":  1607053472,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1607053472.6569998,',
                           u'"defaultfilegroup":  "PRIMARY",',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'},',
                           u'{',
                           u'"adb_id":  "49e5c917-8ca9-4b46-b2e8-e25d9ee711e8",',
                           u'"ag_res_id":  "0b38a4e4-8c30-46e8-873e-7cd1b397bfc1",',
                           u'"name":  "test_alwayson_db_2",',
                           u'"sync_state":  1,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  true,',
                           u'"db_id":  6,',
                           u'"owner":  "sa",',
                           u'"lastbackupdate":  1607053472,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1607053472.6569998,',
                           u'"defaultfilegroup":  "PRIMARY",',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'},',
                           u'{',
                           u'"adb_id":  "85dc383a-bf7b-4ab7-8cea-cc52919bdb36",',
                           u'"ag_res_id":  "777c50fd-348e-4686-a622-edd90a4340e1",',
                           u'"name":  "test_alwayson_db_3",',
                           u'"sync_state":  2,',
                           u'"suspended":  false,',
                           u'"version":  852,',
                           u'"isaccessible":  true,',
                           u'"db_id":  7,',
                           u'"owner":  "sa",',
                           u'"lastbackupdate":  1607071252,',
                           u'"collation":  "SQL_Latin1_General_CP1_CI_AS",',
                           u'"createdate":  1607071252.287,',
                           u'"defaultfilegroup":  "PRIMARY",',
                           u'"primaryfilepath":  "C:\\\\Program Files\\\\Microsoft SQL Server\\\\MSSQL13.SQLAON\\\\MSSQL\\\\DATA",',
                           u'"lastlogbackupdate":  -62135596800,',
                           u'"systemobject":  false,',
                           u'"recoverymodel":  1',
                           u'}',
                           u'],',
                           u'"availability_listeners":  [',
                           u'{',
                           u'"id":  "cf2628b9-d180-46e5-9e56-debf65268cd5",',
                           u'"tcp_port":  1433',
                           u'},',
                           u'{',
                           u'"id":  "93ac36cf-1da8-4803-957f-60c38cd55983",',
                           u'"tcp_port":  1426',
                           u'},',
                           u'{',
                           u'"id":  "5869339c-942f-4ef1-b085-d9718db16cd3",',
                           u'"tcp_port":  1425',
                           u'}',
                           u']',
                           u'}']},

            'wsc-node-02\\SQLAO': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"ao_enabled":  null,',
                           u'"availability_groups":  [',
                           u'],',
                           u'"availability_replicas":  [',
                           u'],',
                           u'"availability_databases":  [',
                           u'],',
                           u'"availability_listeners":  [',
                           u']',
                           u'}']},

            'wsc-node-03\\SQLAO': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"ao_enabled":  null,',
                           u'"availability_groups":  [',
                           u'],',
                           u'"availability_replicas":  [',
                           u'],',
                           u'"availability_databases":  [',
                           u'],',
                           u'"availability_listeners":  [',
                           u']',
                           u'}']}
        }

        result = {}
        for key in response.keys():
            if key in sql_instance_connections_string:
                result = response[key]
                break

        response_object = self.create_sql_commander_response(result)

        return self.defer_sql_commander_response(response_object)


class DummyAlwaysOnStrategiesResponse(ObjectFromDictProducer):

    def __init__(self):
        pass

    def config_from_dict(self, data):
        """
        Returns Object because the calling code expect object, not a dict.
        :param data: dict
        :return: DummyClass
        """

        result_object = DummyClass()

        for key, value in data.iteritems():
            if key == 'datasources' and isinstance(value, list):
                # For datasources need to create list with objects
                original_value = value
                value = []
                for datasource in original_value:
                    datasource_object = self.object_from_dict(datasource)
                    # process datasource 'points' separately as objects
                    datasource_points = datasource.get('points', [])
                    points = []
                    for _, point_id in datasource_points:
                        points.append(self.object_from_dict({'id': point_id}))
                    datasource_object.points = points
                    value.append(datasource_object)
            setattr(result_object, key, value)

        return result_object

    def get_ao_ag_strategy_response(self):

        preprocessing_data = {

            'config_data': {
                'datasources': [
                    {'cluster_node_server': 'wsc-node-02.sol-win.lab//WSC-NODE-02\\SQLAON',
                     'eventClass': '',
                     'params': {'winsqlinstance_id': 'WSC-NODE-02_SQLAON',
                                'contextrelname': 'winsqlavailabilitygroups',
                                'instanceid': '777c50fd-348e-4686-a622-edd90a4340e1',
                                'contexttitle': 'TestAG1', 'contextcompname': 'os',
                                'strategy': 'powershell MSSQL AO AG',
                                'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLAvailabilityGroup'},
                     'template': 'WinAvailabilityGroup',
                     'eventKey': '',
                     'component': '777c50fd-348e-4686-a622-edd90a4340e1', 'device': '10.88.122.130',
                     'points': [({}, 'IsOnline'), ({}, 'NumberOfDisconnectedReplicas'),
                                ({}, 'NumberOfNotSynchronizedReplicas'),
                                ({}, 'NumberOfNotSynchronizingReplicas'), ({}, 'NumberOfReplicasWithUnhealthyRole'),
                                ({}, 'NumberOfSynchronizedSecondaryReplicas')], 'zWinRMPort': '5985',
                     'datasource': 'AvailabilityGroupState'}],
                'manageIp': '10.88.122.130', 'id': '10.88.122.130'},

            'response_data': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"TestAG1":  {',
                           u'"ag_info":  {',
                           u'"primary_replica_server_name":  "WSC-NODE-02\\\\SQLAON",',
                           u'"health_check_timeout":  30000,',
                           u'"automated_backup_preference":  2,',
                           u'"is_clustered_instance":  false,',
                           u'"synchronization_health":  2,',
                           u'"primary_recovery_health":  1',
                           u'},',
                           u'"ag_state":  {',
                           u'"IsOnline":  true,',
                           u'"IsAutoFailover":  true,',
                           u'"NumberOfSynchronizedSecondaryReplicas":  1,',
                           u'"NumberOfNotSynchronizingReplicas":  0,',
                           u'"NumberOfNotSynchronizedReplicas":  0,',
                           u'"NumberOfReplicasWithUnhealthyRole":  0,',
                           u'"NumberOfDisconnectedReplicas":  0',
                           u'},',
                           u'"cl_quorum_state":  1',
                           u'}',
                           u'}']}
        }

        config = self.config_from_dict(preprocessing_data['config_data'])
        response = self.object_from_dict(preprocessing_data['response_data'])

        return config, response

    def get_ao_ar_strategy_response(self):

        preprocessing_data = {
            'config_data': {'datasources': [
                {'cluster_node_server': 'wsc-node-03.sol-win.lab//WSC-NODE-03\\SQLAON',
                 'eventClass': '',
                 'params': {'resource': 'AvailabilityReplicaState', 'contextrelname': 'winsqlavailabilityreplicas',
                            'instanceid': '8974cff2-f04e-4399-96b5-1f256f632e6d',
                            'contexttitle': 'WSC-NODE-03\\SQLAON',
                            'contextcompname': 'os/winsqlavailabilitygroups/777c50fd-348e-4686-a622-edd90a4340e1',
                            'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLAvailabilityReplica',
                            'instancename': 'SQLAON', 'availability_group_name': 'TestAG1'},
                 'eventKey': '',
                 'component': '8974cff2-f04e-4399-96b5-1f256f632e6d',
                 },
                {'cluster_node_server': 'wsc-node-03.sol-win.lab//WSC-NODE-03\\SQLAON',
                 'eventClass': '',
                 'params': {'resource': 'AvailabilityReplicaState', 'contextrelname': 'winsqlavailabilityreplicas',
                            'instanceid': '106864b6-f741-4b3c-b6be-48daa15ff3d7',
                            'contexttitle': 'WSC-NODE-03\\SQLAON',
                            'contextcompname': 'os/winsqlavailabilitygroups/0b38a4e4-8c30-46e8-873e-7cd1b397bfc1',
                            'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLAvailabilityReplica',
                            'instancename': 'SQLAON', 'availability_group_name': 'TestAG'},
                 'eventKey': '',
                 'component': '106864b6-f741-4b3c-b6be-48daa15ff3d7',
                 }],
                'manageIp': '10.88.122.130',
                'id': '10.88.122.130'},

            'response_data': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"8974cff2-f04e-4399-96b5-1f256f632e6d":  {',
                           u'"id":  "8974cff2-f04e-4399-96b5-1f256f632e6d",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"role":  2,',
                           u'"state":  1,',
                           u'"operational_state":  2,',
                           u'"availability_mode":  0,',
                           u'"connection_state":  1,',
                           u'"synchronization_state":  1,',
                           u'"failover_mode":  1,',
                           u'"synchronization_health":  2',
                           u'},',
                           u'"106864b6-f741-4b3c-b6be-48daa15ff3d7":  {',
                           u'"id":  "106864b6-f741-4b3c-b6be-48daa15ff3d7",',
                           u'"name":  "WSC-NODE-03\\\\SQLAON",',
                           u'"role":  2,',
                           u'"state":  1,',
                           u'"operational_state":  2,',
                           u'"availability_mode":  0,',
                           u'"connection_state":  1,',
                           u'"synchronization_state":  1,',
                           u'"failover_mode":  1,',
                           u'"synchronization_health":  2',
                           u'}',
                           u'}']}
        }

        config = self.config_from_dict(preprocessing_data['config_data'])
        response = self.object_from_dict(preprocessing_data['response_data'])

        return config, response

    def get_ao_al_strategy_response(self):

        preprocessing_data = {
            'config_data': {'datasources': [
                {'eventClass': '',
                 'params': {
                     'contextrelname': 'winsqlavailabilitylisteners',
                     'instanceid': '5869339c-942f-4ef1-b085-d9718db16cd3',
                     'contexttitle': 'TestAG1_TestAG_Listener',
                     'contextcompname': 'os/winsqlavailabilitygroups/777c50fd-348e-4686-a622-edd90a4340e1',
                     'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLAvailabilityListener',
                     'instancename': 'SQLAON', 'availability_group_name': 'TestAG1'},
                 'eventKey': '',
                 'component': '5869339c-942f-4ef1-b085-d9718db16cd3'}],
                'manageIp': '10.88.122.130',
                'id': '10.88.122.130'},

            'response_data': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"name":  "TestAG1_TestAG_Listener",',
                           u'"dns_name":  "TestAG_Listener",',
                           u'"state":  "2",',
                           u'"ip_address":  "10.88.123.201"',
                           u'}']}
        }

        config = self.config_from_dict(preprocessing_data['config_data'])
        response = self.object_from_dict(preprocessing_data['response_data'])

        return config, response

    def get_ao_adb_strategy_response(self):

        preprocessing_data = {
            'config_data': {
                'datasources': [
                    {'cluster_node_server': 'wsc-node-02.sol-win.lab//WSC-NODE-02\\SQLAON',
                     'eventClass': '',
                     'component': 'WSC-NODE-02_SQLAON6',
                     'points': [({}, 'ActiveTransactions')],
                     'params': {
                         'database_index': '6', 'resource': 'Active Transactions',
                         'contextrelname': 'databases',
                         'instanceid': 'WSC-NODE-02_SQLAON6',
                         'contexttitle': 'test_alwayson_db_2',
                         'contextcompname': 'os/winsqlinstances/WSC-NODE-02_SQLAON',
                         'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLDatabase',
                     },
                     'eventKey': '',
                     'datasource': 'ActiveTransactions'
                     },
                    {'cluster_node_server': 'wsc-node-02.sol-win.lab//WSC-NODE-02\\SQLAON',
                     'eventClass': '/Status',
                     'component': 'WSC-NODE-02_SQLAON6',
                     'points': [({}, 'ActiveTransactions')],
                     'params': {
                         'database_index': '6', 'resource': '',
                         'contextrelname': 'databases',
                         'instanceid': 'WSC-NODE-02_SQLAON6',
                         'contexttitle': 'test_alwayson_db_2',
                         'contextcompname': 'os/winsqlinstances/WSC-NODE-02_SQLAON',
                         'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLDatabase'
                     },
                     'eventKey': '',
                     'datasource': 'status'
                     },
                    {'cluster_node_server': 'wsc-node-02.sol-win.lab//WSC-NODE-02\\SQLAON',
                     'eventClass': '',
                     'component': 'WSC-NODE-02_SQLAON7',
                     'points': [({}, 'ActiveTransactions')],
                     'params': {
                         'database_index': '7', 'resource': 'Active Transactions',
                         'contextrelname': 'databases', 'instanceid': 'WSC-NODE-02_SQLAON7',
                         'contexttitle': 'test_alwayson_db_3',
                         'contextcompname': 'os/winsqlinstances/WSC-NODE-02_SQLAON',
                         'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLDatabase'},
                     'eventKey': '',
                     'datasource': 'ActiveTransactions'
                     },
                    {'cluster_node_server': 'wsc-node-02.sol-win.lab//WSC-NODE-02\\SQLAON',
                     'eventClass': '/Status',
                     'component': 'WSC-NODE-02_SQLAON7',
                     'points': [({}, 'ActiveTransactions')],
                     'params': {
                         'database_index': '7', 'resource': '', 'contextrelname': 'databases',
                         'instanceid': 'WSC-NODE-02_SQLAON7',
                         'contexttitle': 'test_alwayson_db_3',
                         'contextcompname': 'os/winsqlinstances/WSC-NODE-02_SQLAON',
                         'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLDatabase'},
                     'eventKey': '',
                     'datasource': 'status'
                     },
                    {'cluster_node_server': 'wsc-node-02.sol-win.lab//WSC-NODE-02\\SQLAON',
                     'eventClass': '',
                     'component': 'WSC-NODE-02_SQLAON5',
                     'points': [({}, 'ActiveTransactions')],
                     'params': {
                         'database_index': '5',
                         'resource': 'Active Transactions',
                         'contextrelname': 'databases', 'instanceid': 'WSC-NODE-02_SQLAON5',
                         'contexttitle': 'test_alwayson_db_1',
                         'contextcompname': 'os/winsqlinstances/WSC-NODE-02_SQLAON',
                         'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLDatabase'
                     },
                     'eventKey': '',
                     'datasource': 'ActiveTransactions'
                     },
                    {'cluster_node_server': 'wsc-node-02.sol-win.lab//WSC-NODE-02\\SQLAON',
                     'eventClass': '/Status',
                     'component': 'WSC-NODE-02_SQLAON5',
                     'points': [({}, 'ActiveTransactions')],
                     'params': {'database_index': '5',
                                'resource': '',
                                'contextrelname': 'databases', 'instanceid': 'WSC-NODE-02_SQLAON5',
                                'contexttitle': 'test_alwayson_db_1',
                                'contextcompname': 'os/winsqlinstances/WSC-NODE-02_SQLAON',
                                'contextmodname': 'ZenPacks.zenoss.Microsoft.Windows.WinSQLDatabase'
                                },
                     'eventKey': '',
                     'datasource': 'status'
                     }],
                'id': '10.88.122.130'
            },

            'response_data': {
                'exit_code': 0,
                'stderr': [],
                'stdout': [u'{',
                           u'"model_data":  {',
                           u'"5":  {',
                           u'"status":  "Normal",',
                           u'"sync_state":  1,',
                           u'"suspended":  false',
                           u'},',
                           u'"6":  {',
                           u'"status":  "Normal",',
                           u'"sync_state":  1,',
                           u'"suspended":  false',
                           u'},',
                           u'"7":  {',
                           u'"status":  "Normal",',
                           u'"sync_state":  2,',
                           u'"suspended":  false',
                           u'}',
                           u'},',
                           u'"perf_data":  {',
                           u'"7":  {',
                           u'"Data File(s) Size (KB)":  "8192",',
                           u'"Log File(s) Size (KB)":  "8184",',
                           u'"Log File(s) Used Size (KB)":  "792",',
                           u'"Percent Log Used":  "9",',
                           u'"Active Transactions":  "0",',
                           u'"Transactions/sec":  "34636",',
                           u'"Repl. Pending Xacts":  "0",',
                           u'"Repl. Trans. Rate":  "0",',
                           u'"Log Cache Reads/sec":  "0",',
                           u'"Log Cache Hit Ratio":  "0",',
                           u'"Log Cache Hit Ratio Base":  "0",',
                           u'"Bulk Copy Rows/sec":  "0",',
                           u'"Bulk Copy Throughput/sec":  "0",',
                           u'"Backup/Restore Throughput/sec":  "0",',
                           u'"DBCC Logical Scan Bytes/sec":  "0",',
                           u'"Shrink Data Movement Bytes/sec":  "0",',
                           u'"Log Flushes/sec":  "0",',
                           u'"Log Bytes Flushed/sec":  "0",',
                           u'"Log Flush Waits/sec":  "0",',
                           u'"Log Flush Wait Time":  "0",',
                           u'"Log Truncations":  "0",',
                           u'"Log Growths":  "0",',
                           u'"Log Shrinks":  "0",',
                           u'"Cache Hit Ratio":  "477566",',
                           u'"Cache Hit Ratio Base":  "661720",',
                           u'"Cache Entries Count":  "114",',
                           u'"Cache Entries Pinned Count":  "0"',
                           u'},',
                           u'"5":  {',
                           u'"Data File(s) Size (KB)":  "8192",',
                           u'"Log File(s) Size (KB)":  "8184",',
                           u'"Log File(s) Used Size (KB)":  "811",',
                           u'"Percent Log Used":  "9",',
                           u'"Active Transactions":  "0",',
                           u'"Transactions/sec":  "10916",',
                           u'"Repl. Pending Xacts":  "0",',
                           u'"Repl. Trans. Rate":  "0",',
                           u'"Log Cache Reads/sec":  "0",',
                           u'"Log Cache Hit Ratio":  "0",',
                           u'"Log Cache Hit Ratio Base":  "0",',
                           u'"Bulk Copy Rows/sec":  "0",',
                           u'"Bulk Copy Throughput/sec":  "0",',
                           u'"Backup/Restore Throughput/sec":  "0",',
                           u'"DBCC Logical Scan Bytes/sec":  "0",',
                           u'"Shrink Data Movement Bytes/sec":  "0",',
                           u'"Log Flushes/sec":  "0",',
                           u'"Log Bytes Flushed/sec":  "0",',
                           u'"Log Flush Waits/sec":  "0",',
                           u'"Log Flush Wait Time":  "0",',
                           u'"Log Truncations":  "0",',
                           u'"Log Growths":  "0",',
                           u'"Log Shrinks":  "0",',
                           u'"Cache Hit Ratio":  "483620",',
                           u'"Cache Hit Ratio Base":  "666493",',
                           u'"Cache Entries Count":  "114",',
                           u'"Cache Entries Pinned Count":  "0"',
                           u'},',
                           u'"6":  {',
                           u'"Data File(s) Size (KB)":  "8192",',
                           u'"Log File(s) Size (KB)":  "8184",',
                           u'"Log File(s) Used Size (KB)":  "810",',
                           u'"Percent Log Used":  "9",',
                           u'"Active Transactions":  "0",',
                           u'"Transactions/sec":  "13068",',
                           u'"Repl. Pending Xacts":  "0",',
                           u'"Repl. Trans. Rate":  "0",',
                           u'"Log Cache Reads/sec":  "0",',
                           u'"Log Cache Hit Ratio":  "0",',
                           u'"Log Cache Hit Ratio Base":  "0",',
                           u'"Bulk Copy Rows/sec":  "0",',
                           u'"Bulk Copy Throughput/sec":  "0",',
                           u'"Backup/Restore Throughput/sec":  "0",',
                           u'"DBCC Logical Scan Bytes/sec":  "0",',
                           u'"Shrink Data Movement Bytes/sec":  "0",',
                           u'"Log Flushes/sec":  "0",',
                           u'"Log Bytes Flushed/sec":  "0",',
                           u'"Log Flush Waits/sec":  "0",',
                           u'"Log Flush Wait Time":  "0",',
                           u'"Log Truncations":  "0",',
                           u'"Log Growths":  "0",',
                           u'"Log Shrinks":  "0",',
                           u'"Cache Hit Ratio":  "476887",',
                           u'"Cache Hit Ratio Base":  "659788",',
                           u'"Cache Entries Count":  "114",',
                           u'"Cache Entries Pinned Count":  "0"',
                           u'}',
                           u'}',
                           u'}']}
        }

        config = self.config_from_dict(preprocessing_data['config_data'])
        response = self.object_from_dict(preprocessing_data['response_data'])

        return config, response


def create_ao_device_proxy():

    device_proxy = DeviceProxy()

    device_proxy_attributes = {
        'zWinRSCodePage': 65001, 'zWinRMLocale': 'en-US', 'zSQLAlwaysOnEnabled': True,
        'zWinTrustedKDC': '',
        'zWinKDC': '10.10.10.1', 'zWinUseWsmanSPN': False,
        'zDBInstances': '[{"instance": "MSSQLSERVER", "user": "%s", "passwd": "%s"}]' % (HOST_USER_NAME,
                                                                                         HOST_USER_PASSWORD),
        'zWinTrustedRealm': '', 'getDeviceClassName': '/Server/Microsoft/Cluster',
        'zWinKeyTabFilePath': '', 'kerberos_rdns': False,
        'id': '10.88.122.130', 'skipModelMsg': '', 'zWinRMKRBErrorThreshold': 1,
        '_snmpStatus': -1,
        'windows_user': HOST_USER_NAME, 'zWinRMEnvelopeSize': 512000,
        'zWinRMConnectTimeout': 60,
        'zSQLAlwaysOnReplicaPerfdataNode': 310,
        'windows_servername': 'wsc-cluster.sol-win.lab', 'zWinScheme': 'http',
        'temp_device': True,
        'manageIp': '10.88.122.130', 'zWinRMPort': '5985',
        'windows_password': HOST_USER_PASSWORD, 'zCollectorClientTimeout': 180,
        'zWinRMKrb5includedir': ''}

    for key, value in device_proxy_attributes.iteritems():
        setattr(device_proxy, key, value)

    return device_proxy
